[2022-01-10T08:29:59.706306+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/"" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/\" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php:130)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Users/zain/my_project_directory/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:186)"} []
[2022-01-10T08:29:59.737684+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T08:29:59.776661+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f432dc"},"request_uri":"http://localhost:8000/_wdt/f432dc","method":"GET"} []
[2022-01-10T08:33:48.505806+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/"" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/\" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php:130)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Users/zain/my_project_directory/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:186)"} []
[2022-01-10T08:33:48.534790+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T08:33:48.582961+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b5852e"},"request_uri":"http://localhost:8000/_wdt/b5852e","method":"GET"} []
[2022-01-10T08:54:15.233707+00:00] php.DEBUG: Warning: file(/proc/mounts): Failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":209,"trace":[{"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":162,"function":"isNfs","class":"Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClearCommand","type":"->"}],"count":1}}} []
[2022-01-10T08:56:11.606166+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/"" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/\" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php:130)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Users/zain/my_project_directory/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:186)"} []
[2022-01-10T08:56:11.635346+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T08:56:11.678158+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"51ee56"},"request_uri":"http://localhost:8000/_wdt/51ee56","method":"GET"} []
[2022-01-10T08:57:10.359023+00:00] php.DEBUG: Warning: file(/proc/mounts): Failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":209,"trace":[{"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":162,"function":"isNfs","class":"Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClearCommand","type":"->"}],"count":1}}} []
[2022-01-10T09:08:20.025687+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/"" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/\" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php:130)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Users/zain/my_project_directory/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:186)"} []
[2022-01-10T09:08:20.036732+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:08:20.062860+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"680cfa"},"request_uri":"http://localhost:8000/_wdt/680cfa","method":"GET"} []
[2022-01-10T09:09:08.222954+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-01-10T09:09:08.225862+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:09:08.232637+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:09:08.249896+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"940ae2"},"request_uri":"http://localhost:8000/_wdt/940ae2","method":"GET"} []
[2022-01-10T09:10:27.929963+00:00] php.DEBUG: Warning: file(/proc/mounts): Failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":209,"trace":[{"file":"/Users/zain/my_project_directory/vendor/symfony/framework-bundle/Command/CacheClearCommand.php","line":162,"function":"isNfs","class":"Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClearCommand","type":"->"}],"count":1}}} []
[2022-01-10T09:11:50.562843+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/lucky/number"" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/lucky/number\" at /Users/zain/my_project_directory/vendor/symfony/http-kernel/EventListener/RouterListener.php:130)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lucky/number/\". at /Users/zain/my_project_directory/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2022-01-10T09:11:50.580975+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:11:50.581428+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:11:50.628671+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"fb31e1"},"request_uri":"http://localhost:8000/_wdt/fb31e1","method":"GET"} []
[2022-01-10T09:30:13.590038+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:30:13.590418+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:30:13.604769+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:30:13.625566+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"85b0fc"},"request_uri":"http://localhost:8000/_wdt/85b0fc","method":"GET"} []
[2022-01-10T09:50:16.712205+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:50:16.713796+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:50:16.724116+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:50:16.748828+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5f5e32"},"request_uri":"http://localhost:8000/_wdt/5f5e32","method":"GET"} []
[2022-01-10T09:50:18.537537+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:50:18.538182+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:50:18.544669+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:50:18.572262+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0fb69d"},"request_uri":"http://localhost:8000/_wdt/0fb69d","method":"GET"} []
[2022-01-10T09:50:29.110723+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:50:29.111683+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:50:29.125244+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:51:50.701378+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:51:50.701732+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:51:50.702034+00:00] php.CRITICAL: Uncaught Error: Symfony\Bundle\FrameworkBundle\Controller\AbstractController::render(): Argument #3 ($response) must be of type ?Symfony\Component\HttpFoundation\Response, array given, called in /Users/zain/my_project_directory/src/Controller/LearningController.php on line 23 {"exception":"[object] (TypeError(code: 0): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController::render(): Argument #3 ($response) must be of type ?Symfony\\Component\\HttpFoundation\\Response, array given, called in /Users/zain/my_project_directory/src/Controller/LearningController.php on line 23 at /Users/zain/my_project_directory/vendor/symfony/framework-bundle/Controller/AbstractController.php:226)"} []
[2022-01-10T09:51:50.702853+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Symfony\Bundle\FrameworkBundle\Controller\AbstractController::render(): Argument #3 ($response) must be of type ?Symfony\Component\HttpFoundation\Response, array given, called in /Users/zain/my_project_directory/src/Controller/LearningController.php on line 23" at /Users/zain/my_project_directory/vendor/symfony/framework-bundle/Controller/AbstractController.php line 226 {"exception":"[object] (TypeError(code: 0): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController::render(): Argument #3 ($response) must be of type ?Symfony\\Component\\HttpFoundation\\Response, array given, called in /Users/zain/my_project_directory/src/Controller/LearningController.php on line 23 at /Users/zain/my_project_directory/vendor/symfony/framework-bundle/Controller/AbstractController.php:226)"} []
[2022-01-10T09:51:50.711076+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:51:50.711566+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:51:50.761077+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5f0357"},"request_uri":"http://localhost:8000/_wdt/5f0357","method":"GET"} []
[2022-01-10T09:52:36.151026+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:52:36.151837+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:52:36.157307+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:52:57.109106+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:52:57.110067+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:52:57.124033+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:56:19.850286+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:56:19.851087+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:56:19.854832+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "example.twig" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form)." at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"example.twig\" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form). at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2022-01-10T09:56:19.877605+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:56:19.878303+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:56:19.903557+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1e8e79"},"request_uri":"http://localhost:8000/_wdt/1e8e79","method":"GET"} []
[2022-01-10T09:57:54.146488+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:57:54.146904+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:57:54.147890+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "example.twig" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form)." at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"example.twig\" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form). at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2022-01-10T09:57:54.158924+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:57:54.159372+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:57:54.199070+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1c7870"},"request_uri":"http://localhost:8000/_wdt/1c7870","method":"GET"} []
[2022-01-10T09:59:47.823158+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T09:59:47.824626+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T09:59:47.829431+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "example.twig" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form)." at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"example.twig\" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form). at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2022-01-10T09:59:47.850679+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:59:47.851346+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T09:59:47.887738+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2085d2"},"request_uri":"http://localhost:8000/_wdt/2085d2","method":"GET"} []
[2022-01-10T10:00:16.795350+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T10:00:16.796319+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T10:00:16.798929+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "example.twig" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form)." at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"example.twig\" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form). at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2022-01-10T10:00:16.821828+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:00:16.822590+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:00:16.852369+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f23f9c"},"request_uri":"http://localhost:8000/_wdt/f23f9c","method":"GET"} []
[2022-01-10T10:01:59.999737+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T10:02:00.000134+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T10:02:00.001132+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "index.html.twig" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form)." at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"index.html.twig\" (looked into: /Users/zain/my_project_directory/templates, /Users/zain/my_project_directory/vendor/symfony/twig-bridge/Resources/views/Form). at /Users/zain/my_project_directory/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2022-01-10T10:02:00.011823+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:02:00.012231+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:02:00.034082+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ac7228"},"request_uri":"http://localhost:8000/_wdt/ac7228","method":"GET"} []
[2022-01-10T10:03:17.115718+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T10:03:17.117135+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T10:03:17.126898+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:15:41.301256+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T10:15:41.302568+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T10:15:41.315291+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2022-01-10T10:30:13.364467+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/zain/my_project_directory/config/routes/dev/web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/zain/Documents/my_project_directory/vendor/symfony/config/Resource/FileResource.php","line":61,"trace":[{"file":"/Users/zain/Documents/my_project_directory/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2022-01-10T10:30:13.423339+00:00] request.INFO: Matched route "aboutme". {"route":"aboutme","route_parameters":{"_route":"aboutme","_controller":"App\\Controller\\LearningController::aboutme"},"request_uri":"http://localhost:8000/aboutme","method":"GET"} []
[2022-01-10T10:30:13.423940+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-01-10T10:30:13.442129+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/Documents/my_project_directory/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/Documents/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/zain/Documents/my_project_directory/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
